Footer
sef-global/academix-frontend pull request #68
Opened 2021-04-25 18:15 UTC by gajindubandara

## Purpose
The purpose of this PR is to fix #65

## Goals
To update the year in the footer

## Approach
Updated the year in the footer

### Screenshots
![Screenshot from 2021-04-25 23-44-18](https://user-images.githubusercontent.com/63200586/116004413-3c8d7580-a620-11eb-998d-08c9b9ac1682.png)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2021-04-27 05:57 UTC, Gimhan-minion approved these changes

2021-04-27 10:00 UTC, Gravewalker666 requested changes
Instead of just putting the text, shall we use `Javascript` to make it dynamic?
I think the method is to make a new Date object and use the `.getYear()` function on it, but I'm not sure.

2021-05-01 13:42 UTC, gajindubandara commented
> Instead of just putting the text, shall we use `Javascript` to make it dynamic?
> I think the method is to make a new Date object and use the `.getYear()` function on it, but I'm not sure.

Sure I'll do it

2021-05-02 10:18 UTC, Gravewalker666 approved these changes
Good work, @gajindubandara 
Thanks

2021-05-02 10:19 UTC, merged